#!/bin/bash

rmAdMenu()
{
   sudo rm /etc/grub.d/10_linux
   sudo cp /etc/grubcfg/newcfgs/10_linuxNoMenu /etc/grub.d/10_linuxNoMenu
   sudo chmod +x /etc/grub.d/10_linuxNoMenu
   sudo chgrp root /etc/grub.d/10_linuxNoMenu
   sudo chown root /etc/grub.d/10_linuxNoMenu
}
rmMemOpts()
{
   sudo rm /etc/grub.d/20_memtest86+
}


if [ "$1" == '--clean' ]; then
   echo "cleaning grub";
   rmAdMenu
   rmMemOpts
elif [ "$1" == '--restore' ]; then
   echo "restoring previos grub";
   sudo rm -rf /etc/grub.d
   sudo cp -rf /etc/grubcfg/backups/orig /etc/grub.d
else
	echo "Usage: '--clean' or '--restore' as 1st argument"
fi

sudo update-grub

